<%
DIM suffix
if menuid=269 then 
	response.write "<table cellpadding=""0"" cellspacing=""0"" border=""0"">"
	if pageid=298 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/298.asp"">Trackliste</a></td></tr>"
	if pageid=300 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/300.asp"">1. Gaia</a></td></tr>"
	if pageid=303 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/303.asp"">2. Fra Bagdad til Ground Zero</a></td></tr>"
	if pageid=306 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/306.asp"">3. Dette land - dette folk</a></td></tr>"
	if pageid=309 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/309.asp"">4. Fisken</a></td></tr>"
	if pageid=313 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/313.asp"">5. Økologi ka vi li</a></td></tr>"
	if pageid=319 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/319.asp"">6. Jorden ryster</a></td></tr>"
	if pageid=326 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/326.asp"">7. Rabalder</a></td></tr>"
	if pageid=329 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/329.asp"">8. Jorden går under i morgen</a></td></tr>"
	if pageid=332 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/332.asp"">9. Et godtnok temmelig syret aggregat</a></td></tr>"
	if pageid=346 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/346.asp"">10. Forårsmarch / Grøn Lennon</a></td></tr>"
	if pageid=349 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/349.asp"">11. Tænk hvis – måske</a></td></tr>"
	if pageid=352 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/352.asp"">12. Hvad har min bror gjort</a></td></tr>"
	if pageid=354 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/354.asp"">13. Store avancer</a></td></tr>"
	if pageid=356 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/356.asp"">14. Internationale</a></td></tr>"
	if pageid=426 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/426.asp"">Bonus: Sirius – Troen og håbet</a></td></tr>"
	if pageid=427 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/427.asp"">Bonus: Fuglekvidder</a></td></tr>"
	response.write "</table>"
end if
if menuid=270 then 
	response.write "<table cellpadding=""0"" cellspacing=""0"" border=""0"">"
	if pageid=363 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/363.asp"">ROCK MED!</a></td></tr>"
	if pageid=383 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/383.asp"">Focus på Bæredygtig Udvikling</a></td></tr>"
	if pageid=365 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/365.asp"">Cover noter</a></td></tr>"
	if pageid=366 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/366.asp"">Hjertelig tak</a></td></tr>"
	if pageid=370 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/370.asp"">Links</a></td></tr>"
	if pageid=372 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/372.asp"">Øko-net</a></td></tr>"
	response.write "</table>"
end if
if menuid=378 then 
	response.write "<table cellpadding=""0"" cellspacing=""0"" border=""0"">"
	if pageid=379 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/379.asp"">Billeder</a></td></tr>"
	if pageid=468 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/468.asp"">Invitation til reception</a></td></tr>"
	if pageid=469 then suffix="Sel" else suffix=""
	response.write "<tr><td class=""leftmenuTD"&suffix&"""><a href=""/pages/469.asp"">Pressemeddelelse 20. maj</a></td></tr>"
	response.write "</table>"
end if

%>